### PR TITLE
Avoid using Infura Provider

### LINKED ISSUE #2056: Persistent Seeder not working

### PR DESCRIPTION
**Pull request by lalexgap**
As far as I can tell `InfuraProvider` is not working right now (see https://github.com/ethers-io/ethers.js/issues/868)

This PR disables it until the issue resolves so the persistent seeder will function.

Fixes #2056

### CODE REVIEW

File: packages/xstate-wallet/src/utils/contract-utils.ts [hunk 1]
```diff
@@ -28,7 +28,10 @@ export function getProvider(): Web3Provider | JsonRpcProvider {
   if (provider) return provider;
 
   if (window.ethereum) {
-    if (window.ethereum.mockingInfuraProvider) {
+    // TODO: Currently disabled due to InfuraProvider not working
+    // see  https://github.com/ethers-io/ethers.js/issues/868
+    // eslint-disable-next-line no-constant-condition
+    if (window.ethereum.mockingInfuraProvider && false) {
```
Comment (andrewgordstewart) [inline packages/xstate-wallet/src/utils/contract-utils.ts:34]: Enable infura provider for persistent seeder

**Comment by andrewgordstewart** [comment]
Thanks for sorting this out. This error was thrown by the [`e2e-test-w3t-production`](https://app.circleci.com/pipelines/github/statechannels/monorepo/7142/workflows/20fe39f2-6a45-4854-8463-f0387111847e/jobs/32516) test, and I had no idea what it was.
