### PR TITLE
[WIP] Fix inconsistent pricing 

### LINKED ISSUE #1148: [web3t] Fix inconsistent pricing
If I download a file that claims to "cost" 1300 wei, why do I end up paying far more than that? (Paying a little more is expected and probably ok, since we are using a basic buffered payment system).

### PR DESCRIPTION
**Pull request by spersico**
This PR should close #1148

There were quite a lot of issues that caused the issue:
- The **STOP** and **START** messages were being emitted and handled several times (on response to each blocked request). This provoked that sometimes funds were being transferred more than once. It also affected the process of jumpstarting the download and provoked several inconsistencies.
**Solutions:** 
I added a message interceptor at the wire level, that automates things, avoids message repetition at the leecher side, and adds some encapsulation to the wire.
I also added more checks in the stop() and start() methods to avoid spamming the leecher with messages, if possible.

- _The **REQUEST** interceptor implementation was horrible_, and I hate myself for leaving it as it was 'till now. It was hard to read and understand, and it seems that it added inconsistencies in its execution, provoked, I believe, by the stack not being always the same.
**Solution:**
I now pass a callback with the REQUEST event, that gives the client the power to allow or block a request.

- _The **STOP** and  **START** logic was/is problematic:_ for some reason, as it was (and until an hour ago) if the seeder choked the leecher, but the leecher had still some responses of requests left to process, all those responses got dropped. 
**Solution:**
I make the seeder wait 'till it finishes to process all requests (_by using setTimeout, yes, I hate it, I need to see if I can avoid it_), and only then emit the START event. 

Besides that, I added some more improvements to the codebase:
- Now we can see when a request is responded (by intercepting the _onPiece method).
- I merged the listeners of the **REQUEST** event to a single one so that it gets easier to read, and all requests share the same interface and behaviour.
- I removed unnecessary method calls in the jumpstart function (I believe they were unnecessary, but we don't have the tests that could help check that, like the one that tested if the leecher could start downloading files after 2+ minutes idle).

**Everything seems to be working, but I need to do some more manual testing. With the last basic runs that I made to test this, it worked great, but if someone else wants to give it a run, that would be great.**

### CODE REVIEW

File: packages/web3torrent/src/library/paid-streaming-extension.ts [hunk 1]
```diff
@@ -87,15 +89,19 @@ export abstract class PaidStreamingExtension implements Extension {
...
 
   start() {
-    this.isForceChoking = false;
-    this.wire.unchoke();
-    this.executeExtensionCommand(PaidStreamingExtensionNotices.START);
+    if (this.isForceChoking) {
+      setTimeout(() => {
+        this.isForceChoking = false;
+        this.executeExtensionCommand(PaidStreamingExtensionNotices.START);
+      }, 0);
```
Comment (geoknee) [inline packages/web3torrent/src/library/paid-streaming-extension.ts]: Is this a timeout for 0 ms?

File: packages/web3torrent/src/library/paid-streaming-extension.ts [hunk 2]
```diff
@@ -111,13 +117,36 @@ export abstract class PaidStreamingExtension implements Extension {
...
-      log('ERROR: decoding', err);
+      log('ERROR: onMessage decoding', err);
       return;
     }
   }
 
+  protected messageHandler({command, data}) {
+    switch (command) {
+      case PaidStreamingExtensionNotices.ACK:
+        return;
```
Comment (geoknee) [inline packages/web3torrent/src/library/paid-streaming-extension.ts]: Do you think we ought to use either `return` or `break` exclusively?

File: packages/web3torrent/src/library/paid-streaming-extension.ts [hunk 3]
```diff
@@ -111,13 +117,36 @@ export abstract class PaidStreamingExtension implements Extension {
...
+      case PaidStreamingExtensionNotices.START:
+        log(`START received from ${this.peerAccount}`);
+        this.isBeingChoked = false;
+        this.wire.requests = [];
+        this.wire.unchoke();
```
Comment (geoknee) [inline packages/web3torrent/src/library/paid-streaming-extension.ts]: Could you explain why the leecher is choking/unchoking? Is it their way of reducing unecessary requests to the seeder?

File: packages/web3torrent/src/library/paid-streaming-extension.ts (hunk 1 above)
Comment (snario) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: It is 😕

File: packages/web3torrent/src/library/paid-streaming-extension.ts [hunk 4]
```diff
@@ -111,13 +117,36 @@ export abstract class PaidStreamingExtension implements Extension {
...
-      this.messageBus.emit(PaidStreamingExtensionEvents.NOTICE, jsonData);
+      this.messageHandler(jsonData);
     } catch (err) {
-      log('ERROR: decoding', err);
+      log('ERROR: onMessage decoding', err);
       return;
     }
   }
 
+  protected messageHandler({command, data}) {
```
Comment (snario) [inline packages/web3torrent/src/library/paid-streaming-extension.ts]: Perhaps rename to `handleMessage`?

File: packages/web3torrent/src/library/paid-streaming-extension.ts [hunk 5]
```diff
@@ -111,13 +117,36 @@ export abstract class PaidStreamingExtension implements Extension {
...
+      case PaidStreamingExtensionNotices.START:
+        log(`START received from ${this.peerAccount}`);
+        this.isBeingChoked = false;
+        this.wire.requests = [];
+        this.wire.unchoke();
+        break;
+      case PaidStreamingExtensionNotices.STOP:
+        log(`STOP received from ${this.peerAccount}`);
+        this.peerChannelId = data;
+        if (this.isBeingChoked) return;
```
Comment (snario) [inline packages/web3torrent/src/library/paid-streaming-extension.ts]: Why does this case `return` and skip lines 146 and 147?

File: packages/web3torrent/src/library/web3torrent-lib.ts [hunk 6]
```diff
@@ -27,7 +26,7 @@ export type TorrentCallback = (torrent: Torrent) => any;
 export * from './types';
 
 export const WEI_PER_BYTE = bigNumberify(1); // cost per credit / piece
-export const BUFFER_REFILL_RATE = bigNumberify(100000); // number of credits / pieces the leecher wishes to increase the buffer by
+export const BUFFER_REFILL_RATE = bigNumberify(80000); // number of credits / pieces the leecher wishes to increase the buffer by
```
Comment (snario) [inline packages/web3torrent/src/library/web3torrent-lib.ts]: Perhaps we should put this inside a `constants.ts` file so they're more easily understood to be app-level constants.

File: packages/web3torrent/src/library/web3torrent-lib.ts [hunk 7]
```diff
@@ -140,77 +138,71 @@ export default class WebTorrentPaidStreamingClient extends WebTorrent {
...
-        //   'Seeder Balance: ' + knownPeerAccount.seederBalance
-        // );
-      }
-    });
-
-    wire.paidStreamingExtension.once(
+    wire.paidStreamingExtension.on(
       PaidStreamingExtensionEvents.REQUEST,
-      async (index: number, offset: number, size: number) => {
+      async (index: number, _: number, size: number, response: (allow: boolean) => void) => {
```
Comment (snario) [inline packages/web3torrent/src/library/web3torrent-lib.ts]: Since we use `lodash`, maybe we ought not name a local variable `_`.

File: packages/web3torrent/src/library/web3torrent-lib.ts [hunk 8]
```diff
@@ -343,27 +325,18 @@ export default class WebTorrentPaidStreamingClient extends WebTorrent {
...
     }
+
+    log(`JUMPSTART: Wire requests.`, JSON.stringify(wire.requests, null, 1));
+    torrent.pieces.forEach(piece => {
+      if (piece && !!piece._reservations) {
+        piece._reservations--;
+      }
+    });
+    torrent._update();
+    // torrent._startDiscovery(); // useful for long blocked torrents, forces the client to re-start searching for peers
```
Comment (snario) [inline packages/web3torrent/src/library/web3torrent-lib.ts]: Does the client _stop_ searching for peers at some point?

File: packages/web3torrent/src/library/paid-streaming-extension.ts (hunk 1 above)
Comment (geoknee) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: I read that this is a reasonably common hack, equivalent to some small browser-specific timeout. It's basically the minimum timeout possible.

Comment (snario) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: I saw this once, might explain it https://github.com/feross/queue-microtask

Comment (snario) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: > **Why not use setTimeout(fn, 0)?**
This approach is the most compatible, but it has problems. Modern browsers throttle timers severely, so setTimeout(…, 0) usually takes at least 4ms to run. Furthermore, the throttling gets even worse if the page is backgrounded. If you have many setTimeout calls, then this can severely limit the performance of your program.

Comment (andrewgordstewart) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: What's the purpose of the 0ms timeout here?

**Comment by geoknee** [comment]
I am going to merge this so we can unblock people; the discussion can continue and actions arising should be addressed in followup PRs.

File: packages/web3torrent/src/library/paid-streaming-extension.ts (hunk 1 above)
Comment (spersico) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: The idea is to let the seeder finish responding all the requests that the leecher made. It dont really like this _"solution"_. I could check the _queue-microtask_ package as a replacement,  or no timeout at all.

File: packages/web3torrent/src/library/paid-streaming-extension.ts (hunk 2 above)
Comment (spersico) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: Umm.. maybe, the idea was to avoid an unending cycle of ACKs between peers, and repeating code...  but yeah, it gets harder to read. I could change it in another PR later

Comment (geoknee) [reply packages/web3torrent/src/library/paid-streaming-extension.ts]: If there's a good reason for the difference, then that's fine and you could probably just add a comment (or not). It just popped out at me when I scanned over the code.
